// AUTO-GENERATED by scripts/gen-brand-assets.mjs - do not edit.
//
// Re-exported so the app's pages can use the `@/` alias while the vendored demo
// shells reach the same component by a relative path that resolves in both trees.
export { Logo } from "@/components/BrandLogo";
